### ISSUE TITLE
NIO thread already logged with activemq 5.14

### ISSUE THREAD

**Issue by riccardomodanese** [eurotech/kapua#163]
Hi, 
      after switching from activeMQ 5.11 to 5.14, with the same code base, I noticed this issue.
Very frequently (about 50% of times), the first login attempt I did soon after the broker start will fail because the thread (in that case the NIO nn Thread) is already logged.
I'm pretty sure that this happens because the NIO thread is spanned from another thread created before by Camel.

From the log, when the issue is occuring, it's possible to see the exception from kapua authenticator service:

[shiro_issue_5_14.txt](https://github.com/eurotech/kapua/files/477171/shiro_issue_5_14.txt)

This bug is reproducible into the chng-packageAMQ branch.
Before reproduce it, please remove the lines:

// TODO FIXME: to be removed once we are able to avoid the thread splitting from an already logged thread for the activemq nio worker
ThreadContext.unbindSubject();

in KapuaSecurityBrokerFilter (should be the lines 322-323)

To create the vagrant machine follow this steps:
 - create the vagrant box from dev-tools project (create_kapua_box.sh)
 - start the vagrant machine under developMachine (vagrant up from this directory)
 - mvn clean install -Psql
 - vagrant ssh
 - cd /usr/local/activemq/apache-activemq-5.14.0/
 - start_broker.sh

From the investigations I did for fixing the previous issues we found on Shiro side (with 5.11), it seems that Camel creates n + 1 threads (n is the number of concurrent consumer set in the activemq.xml) but the last concurrent consumer thread is created from the thread that instantiate the vm connection (so alredy logged at the end).

The 5.14 has the same behaviour but also the new one described in that issue.

**Comment by hekonsek** [comment]
Actually current behavior seems to be OK for me. As far as I know ActiveMQ uses threads pool handle incoming connections. It is perfectly normal then that if connection interceptor can see local thread data associated with the previous connection. It is fine, because it is not ActiveMQ responsibility to clean up a local thread data - this is up to the same code that set the thread local to ensure that thread credentials from previous connection has been cleaned before manipulating thread local data.

I would say then that your current workaround (i.e. cleaning Shiro credentials from thread local when new connection is accepted) is a perfectly valid solution and should be kept and documented [1] as such. This is common patterns for such scenarios.

Is there something that concerns you in this approach? Is there any particular reason why you would like to change it?

[1] https://github.com/eurotech/kapua/commit/81029e4e26bc6d4cc9dee2852e58a11438df990b

**Comment by riccardomodanese** [comment]
I agree that activeMQ is not responsible for not cleaned up thread.
The fact that login call found an already logged thread (before my workaround) may be a symptom that something was wrong in other components.
I’ll try to give you a picture of what is happening.
Based on Kapua current configuration Camel should create 10 concurrent consumers subscribed on >.
Looking at the broker startup log I saw this 10 consumers because Camel asks to Kapua customized factory 10 new threads, but at the end it tries to create a new one from one of the previous already logged thread.
(From the log "Instantiate new thread kapuaExecutorThreadFactory_11 from thread kapuaExecutorThreadFactory_1 …”)
Since Shiro uses inherited thread local this will lead to an exception from our authentication service because the new thread will already have an authenticated Shiro subject.
So to avoid this issue I added code to the KapuaRunnableFactory to check if the thread is logged or not. In case it’s logged the KapuaRunnableFactory skips the new login and (depending on the revisions I wrote) rebind the cloned KapuaSession object to the new thread context (because KapuaSession is not an inheritable thread context).
With this fix another exception will come. This exception doesn’t happen every time, but about in 50% of the test I did.
Looking at the log (see issue #156), it’s possible to see an unauthenticated context exception from a thread that always is the authenticated thread form which the 11st thread is created.
I don’t understand how it’s possible since I don’t do any logout in this thread when creating the new runnable.
I can explain myself better this afternoon, in the incoming call if you agree.

**Comment by hekonsek** [comment]
Just to be sure - `addExternalConnection` is called when new incoming connection is started, right?

If so, then we should clean the thread local on the beginning of this method before trying to log in.

**Comment by hekonsek** [comment]
Are my assumptions right? :)

**Comment by riccardomodanese** [comment]
yes, it's called by the new incoming login.
I agree regarding the clean up before the login, may be a good idea to do so.
But unfortunately, with this fix, I'm seeing the exception described in the issue #156 (unauthenticated thread).
Do you have any idea about that?

**Comment by hekonsek** [comment]
I propose then to close this issue and settle an agreement that we should log out user from thread on new connection. Then we should focus on resoling #156 as it seems to be the real problem here.

Sounds like a plan? :)

**Comment by riccardomodanese** [comment]
I agree with you for the logout every login attempts.
In any case I’m not sure that the issue I saw before this forced logout was unrelated to the issue #156.
Tomorrow I’ll open again the issue #156 (or I’ll create a new one).
In any case I don’t understand why the already authenticated thread from which a new thread is created by the KapuaThreadFactory, will result unauthenticated soon after.
The Shiro configuration seems correct.

**Comment by riccardomodanese** [comment]
I close this issue since I just repoen the #156

**Comment by hekonsek** [comment]
I will try to help you with #156 then.
