### ISSUE TITLE
APIs - contribute Account service API

### ISSUE THREAD

**Issue by stefanomorson** [eurotech/kapua#169]
The issue has been started as part of the first APIs contribution (#168).
Generally speaking when contributing a service in the APIs the following has to be done:

1. Create the resource object under app.api.resource package
2. Move serialization annotations (@Xml...) from implementation model objects to interface model objects (example in account service)
  - Pay attention to add @XmlAdapter notation for KapuaId fields
  - Pay attention to add factory method in @XmlType annotation
3. Add serialization annotation to service specific query result list object (example in account service)
3. Review the new @XmlType#propOrder list since fields can be changed compared to the past
4. Add a XmlRegistry class implementing bean creation behind interface model objects (example in account service)
5. Add the top level model objects and the registry class into the managed objects list within the app.api.JaxbContextResolver class

The pattern is repeatibel for every account

**Comment by Coduz** [comment]
@Lorthirk  Can this issue be marked as an Epic for REST API integration in Kapua?
