### ISSUE TITLE
KapuaEntity objects' scopeId is not deserialized

### ISSUE THREAD

**Issue by Lorthirk** [eurotech/kapua#181]
This happens because of `KapuaEntity` not requiring a public setter for scopeId

**Comment by Lorthirk** [comment]
@stefanomorson we need to investigate further on how to act properly to solve this issue. Actually setting only the scopeId is not enough, since other fields are needed (createdOn, createdBy, modifiedOn, modifiedBy) but we need to understand the implications. I'm also closing the PR #182 to avoid to get it merged before we finalize it.

**Comment by stefanomorson** [comment]
@Lorthirk , @Coduz : I was looking at the viable solutions, possibly without breaking the contracts that we have. Actually the issue (unmarshalling don't set the scopeId property) affects the createdOn/createdBy and modifiedOn/modifiedBy as well. The problem shows with the update operations invoked by the rest API.

I think we were right at the beginning when we thought to make this properties "read only" (scopeId is not read-only just for the creators). 

My idea is to manage this stuff on the implementation side and specifically in ServiceDAO:

```
    public static <E extends KapuaEntity> E update(EntityManager em, Class<E> clazz, E entity)
    {
        //
        // Checking existence
        E entityToUpdate = em.find(clazz, entity.getId());

        ...
    }
```

Actually, in my understanding, ServiceDAO was created not to give a super generic DAO that works with every implementation of KapuaEntity but more as an helper class that puts together some common code for reusability. In all the DAOs that use ServiceDAO we already cast entities to implementations, for example in AccountDAO (and others) we do the following:

```
    public static Account update(EntityManager em, Account account)
        throws KapuaException
    {
        //
        // Update account
        AccountImpl accountImpl = (AccountImpl) account;

        return ServiceDAO.update(em, AccountImpl.class, accountImpl);
    }
 ```

So my proposal is the following, change a bit the ServiceDAO implementation in:

```
    public static <E extends KapuaEntity> E update(EntityManager em, Class<E> clazz, E entity)
    {
        //
        // Checking existence
        AbstractKapuaEntity entityToUpdate = (AbstractKapuaEntity)em.find(clazz, entity.getId());
        entity.setScopeId(entityToUpdate.getScopeId());
        entity.setCreatedBy(entityToUpdate.getCreatedBy());
        entity.setCreatedOn(entityToUpdate.getCreatedOn());
        if (entity implements AbstractKapuaUpdatableEntity) {
                AbstractKapuaUpdatableEntity updatableEntity = (AbstractKapuaUpdatableEntity)entity;
                AbstractKapuaUpdatableEntity updEntityToUpdate = (AbstractKapuaUpdatableEntity)entityToUpdate;
                entityToUpdate.setModifiedOn(updEntityToUpdate.getModifiedOn());
                entityToUpdate.setModifiedBy(updEntityToUpdate.getModifiedBy());
        }
        //
        // Deleting if not null
        if (entityToUpdate != null) {
            em.merge(entity);
            em.flush();
            em.refresh(entityToUpdate);
        }

        return entityToUpdate;
    }
```

**Comment by Lorthirk** [comment]
This really close to what I came up with now. I still have one question though: In `org.eclipse.kapua.service.device.registry.event.internal.DeviceEventDAO.update` method we're calling `ServiceDAO.update()` with a `KapuaEntity` implementation that doesn't not inherit from `AbstractKapuaUpdatableEntity` (and thus does not implement `KapuaUpdatableEntity`):

``` 
public static DeviceEvent update(EntityManager em, DeviceEvent deviceConnection)
        throws KapuaException
    {
        DeviceEventImpl deviceConnectionImpl = (DeviceEventImpl) deviceConnection;
        return ServiceDAO.update(em, DeviceEventImpl.class, deviceConnectionImpl);
    }
```
Is this right, or DeviceEventImpl should indeed inherit from `AbstractKapuaUpdatableEntity`?

**Comment by Lorthirk** [comment]
After reviewing this with @riccardomodanese we decided to let the REST endpoints to set the `scopeId` before calling the implementation service, in order to pass the validation in it; instead, we're setting `modifiedOn` and `modifiedBy` in `ServiceDAO.update()`
