### ISSUE TITLE
Dependencies issues and header files

### ISSUE THREAD

**Issue by stefanomorson** [eurotech/kapua#197]
Here's the list of files that seem to have non-Eurotech copyright:

- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/lib/es5-shim.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/lib/handlebars-4.0.5.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/lib/jquery.ba-bbq.min.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/lib/jquery.ba-bbq.min.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/lib/marked.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/swagger-ui.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/swagger-ui.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/swagger-ui.js
- [x] ./org.eclipse.kapua.app.api/src/main/webapp/doc/swagger-ui.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/gxt/desktop/css/desktop.css
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/jquery/jquery-1.4.2.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/jquery/jquery-1.4.2.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/jquery/jquery-1.4.2.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/openlayers.js
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/theme/default/google.css
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/theme/default/google.css
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/theme/default/google.tidy.css
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/theme/default/style.css
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/theme/default/style.css
- [x] ./org.eclipse.kapua.app.console/src/main/webapp/js/openlayers/2.11/theme/default/style.tidy.css

My guess is that e.g in the console webapp folder you will want to get rid of
the jquery and openlayers folders altogether.
In general, the console webapp folder is I think a bit messy still. There's a
binary .swf file that you will probably need to clarify the provenance of, the
desktop.jpg file seem to be 3rd party content too, gxt*.css files are probably
3rd party content from GXT?, etc.

**Comment by Coduz** [comment]
hi @stefanomorson ,

this can be closed right? We have fixed all of this with the release of 0.1.2 version, right?

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi all,

We moved part of the dependencies outside of the code base. 
I'll edit @stefanomorson  message with checkboxes in order to track which files have been fixed and which file need to be managed.

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi @stefanomorson ,

I think that all files have been cleaned. Can you confirm and close the issue?

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi all,

I've checked this, and it's ok in 0.1.6.

I'll close it.

Regards, 

_Alberto_
