### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by stefanomorson** [eurotech/kapua#231]
Remove the following from the code base:

- kapua/org.eclipse.kapua.app.console/src/main/webapp/console
- kapua/org.eclipse.kapua.app.console/src/main/webapp/eclipse
- kapua/org.eclipse.kapua.app.console/src/main/webapp/gxt
- kapua/org.eclipse.kapua.app.console/src/main/java/org/eclipse/kapua/app/console/client/resources/icons/

and manage as dependencies

**Comment by Coduz** [comment]
Hi all,

this issue has been fixed with release-0.1.5 and then it can be closed.

Regards, 

_Alberto_
