### ISSUE TITLE
translator - JavaDoc

### ISSUE THREAD

**Issue by hekonsek** [eurotech/kapua#41]
Notes:
- Add JavaDoc
- Package message.translator? Name?

**Comment by riccardomodanese** [comment]
partiallu done by #222

**Comment by riccardomodanese** [comment]
modules:

- translator
- translator.kapua.kura
- translator.kura.jms
- translator.kura.mqtt

**Comment by riccardomodanese** [comment]
Still missing translator.kapua.kura module
